import type {createUI} from './ui';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
interface ModelContext{registerTool(tool:Tool,options:{signal:AbortSignal}):void|Promise<void>;}
export function registerViewerTools(app:HTMLElement,actions:Pick<ReturnType<typeof createUI>,'showCard'|'assemble'|'getState'>){
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return ()=>{};
  const lifecycle=new AbortController();
  const validate=(input:unknown,key:string,values:string[])=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');const x=input as Record<string,unknown>;if(Object.keys(x).length!==1||typeof x[key]!=='string'||!values.includes(x[key] as string))throw new Error(`Expected ${key}: ${values.join(', ')}`);return x[key] as string;};
  const register=(tool:Tool)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}};
  register({name:'read_temple_view',title:'读取东大殿视图状态',description:'Read the current model mode, camera position and exploded assembly state. Does not change the scene.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return actions.getState();}});
  register({name:'set_temple_view',title:'切换东大殿展示模式',description:'Switch the same visible controls to complete, structure, exploded or demo view. Animations remain interactive.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['complete','structure','exploded','demo']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const mode=validate(input,'mode',['complete','structure','exploded','demo']);actions.assemble();if(mode!=='complete')app.querySelector<HTMLButtonElement>(mode==='structure'?'#structure':mode==='exploded'?'#explode':'#demo')!.click();await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {mode,animation:mode==='demo'?'started':'transition_started'};}});
  register({name:'show_component_card',title:'查看木构知识卡片',description:'Open the visible knowledge card for a structural component.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['column','beam','fang','dougong','purlin','rafter','base','roof','ridge','foundation']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const kind=validate(input,'kind',['column','beam','fang','dougong','purlin','rafter','base','roof','ridge','foundation']);actions.showCard(kind);return {kind,card:'open'};}});
  return ()=>lifecycle.abort();
}
